---
blank_issues_enabled: false
contact_links:
  - name: Exam AZ-304 - Microsoft Azure Architect Design Crash Course Community Support
    url: https://github.com/timothywarner/az304/discussions
    about: Please ask and answer questions here.
